---
spring:
  application:
    name: foo-service
  datasource:
    writer:
      jdbc-url: jdbc:h2:mem:write
      poolName: writer-pool
      minimum-idle: 3
      maximum-pool-size: 15
      read-only: false
      auto-commit: false
    reader:
      jdbc-url: jdbc:h2:mem:read
      poolName: reader-pool
      minimum-idle: 3
      maximum-pool-size: 15
      read-only: true
      auto-commit: false
  jpa:
    properties:
      hibernate:
        connection:
          handling_mode: DELAYED_ACQUISITION_AND_RELEASE_AFTER_TRANSACTION
    hibernate:
      ddl-auto: validate
    open-in-view: false
